# Generated by Django 3.2.13 on 2022-05-11 06:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0002_creditmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='about_content',
            field=tinymce.models.HTMLField(default=1, verbose_name='About Content'),
            preserve_default=False,
        ),
    ]
