# Generated by Django 3.2.13 on 2022-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0004_award_nomination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='drop_time',
            new_name='da_ti',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='birthday',
            field=models.DateTimeField(max_length=200, verbose_name='Date/Time'),
        ),
    ]
