# Generated by Django 3.2.13 on 2022-05-15 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0006_alter_nomination_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='award_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomination',
            name='birthday',
            field=models.CharField(max_length=200, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='select_all',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', ' No'), ('', 'Select')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Doctor', ' Doctor'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('', 'Choose Title')], default='', max_length=40),
        ),
    ]
