# Generated by Django 3.2.13 on 2022-05-15 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0007_auto_20220515_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='member',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
