# Generated by Django 3.2.13 on 2022-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0008_nomination_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name_plural': 'Nomination'},
        ),
    ]
