# Generated by Django 3.2.13 on 2022-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0009_alter_nomination_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Doctor', ' Doctor'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('', 'Choose Title')], default='', max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=200, verbose_name='Home Address')),
                ('email', models.CharField(max_length=40)),
                ('select_all', models.CharField(choices=[('Yes', 'Yes'), ('No', ' No'), ('', 'Select')], default='', max_length=40)),
                ('member', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Principal Nominator',
            },
        ),
    ]
