# Generated by Django 3.2.13 on 2022-05-15 18:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0011_auto_20220515_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emytology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emytology',
            },
        ),
    ]
