# Generated by Django 3.2.13 on 2022-05-29 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0014_community_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
