# Generated by Django 3.2.3 on 2023-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0018_communityarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityarticle',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
