# Generated by Django 3.2.3 on 2023-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0019_communityarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
