# Generated by Django 3.2.3 on 2023-08-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupo_app', '0020_alter_communityarticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityarticle',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Author'),
        ),
    ]
